# Generated by Django 5.0.2 on 2024-03-05 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfContactInfo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pOC_name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email ID')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('remarks', models.CharField(max_length=1024, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectInfo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prospect_name', models.CharField(max_length=255, verbose_name='Name')),
                ('street_loc', models.CharField(max_length=255, verbose_name='Street/Locality')),
                ('city', models.CharField(max_length=50, verbose_name='City/Town/Village')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('email', models.EmailField(max_length=255, verbose_name='Email ID')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('denomination', models.CharField(max_length=50, verbose_name='Denomination')),
                ('congregation', models.IntegerField(verbose_name='Congregation Size (Approx)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
