# Generated by Django 5.0.2 on 2024-03-17 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Prospect Name')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Street/Locality')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='City/Town/Village')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email ID')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='Website')),
                ('denomination', models.CharField(blank=True, max_length=50, null=True, verbose_name='Denomination')),
                ('congregation', models.IntegerField(blank=True, null=True, verbose_name='Congregation Size (Approx)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.state')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email ID')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Number')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_poc', to='prospect.profile')),
            ],
        ),
    ]
