# Generated by Django 5.0.2 on 2024-03-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofcontactinfo',
            name='prospect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prospect.prospectinfo'),
        ),
    ]
