# Generated by Django 5.0.3 on 2024-05-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('initiated', 'First Call/Appointement Requested'), ('meeting scheduled', 'Meeting Scheduled'), ('awaiting', 'Awaiting Response'), ('accepted', 'Responded Yes'), ('rejected', 'Responded No')], max_length=55),
        ),
    ]
