# Generated by Django 5.0.3 on 2024-04-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('initiated', 'First Call'), ('meeting scheduled', 'Meeting Scheduled'), ('awaiting', 'Awaiting Response'), ('trial', 'On Trial Period'), ('accepted', 'Responded Yes'), ('rejected', 'Responded No')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='status',
            field=models.CharField(choices=[('initiated', 'First Call'), ('meeting scheduled', 'Meeting Scheduled'), ('awaiting', 'Awaiting Response'), ('trial', 'On Trial Period'), ('accepted', 'Responded Yes'), ('rejected', 'Responded No')], max_length=55),
        ),
    ]
