# Generated by Django 5.0.2 on 2024-03-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
        ('prospect', '0003_rename_poc_name_pointofcontactinfo_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectinfo',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City/Town/Village'),
        ),
        migrations.AlterField(
            model_name='prospectinfo',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.country'),
        ),
        migrations.AlterField(
            model_name='prospectinfo',
            name='denomination',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Denomination'),
        ),
        migrations.AlterField(
            model_name='prospectinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='prospectinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Prospect Name'),
        ),
        migrations.AlterField(
            model_name='prospectinfo',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.state'),
        ),
        migrations.AlterField(
            model_name='prospectinfo',
            name='street',
            field=models.CharField(max_length=255, null=True, verbose_name='Street/Locality'),
        ),
    ]
