# Generated by Django 5.0.3 on 2024-05-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_alter_profile_status'),
        ('prospect', '0003_alter_pointofcontact_mobile'),
    ]

    operations = [
    ]
