# Generated by Django 5.0.2 on 2024-03-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
        ('prospect', '0004_alter_prospectinfo_city_alter_prospectinfo_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointOfContactInfo',
            new_name='PointOfContact',
        ),
        migrations.RenameModel(
            old_name='ProspectInfo',
            new_name='Profile',
        ),
    ]
