# Generated by Django 5.0.3 on 2024-05-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0004_merge_20240525_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('initiated', 'First Call'), ('meeting scheduled', 'Meeting Scheduled'), ('awaiting', 'Awaiting Response'), ('trial', 'On Trial Period'), ('accepted', 'Responded Yes'), ('rejected', 'Responded No')], max_length=55),
        ),
    ]
