# Generated by Django 5.0.2 on 2024-03-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0005_rename_pointofcontactinfo_pointofcontact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofcontact',
            old_name='contact_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='remarks',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Remarks'),
        ),
    ]
