# Generated by Django 5.0.2 on 2024-03-16 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0006_rename_contact_name_pointofcontact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='prospect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_poc', to='prospect.profile'),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
