# Generated by Django 5.0.2 on 2024-03-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('plan', '0001_initial'),
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prospect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospect.profile'),
        ),
        migrations.AddField(
            model_name='subscribedplan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_plan', to='customer.profile'),
        ),
        migrations.AddField(
            model_name='subscribedplan',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.tariff'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to='customer.profile'),
        ),
        migrations.AddField(
            model_name='userapppermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_app_permissions_customer', to='customer.user'),
        ),
        migrations.AlterUniqueTogether(
            name='userapppermissions',
            unique_together={('user', 'module')},
        ),
    ]
