# Generated by Django 5.0.2 on 2024-02-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerplan',
            old_name='duration_months',
            new_name='duration_in_months',
        ),
        migrations.RenameField(
            model_name='customerplan',
            old_name='plan',
            new_name='subscription_plan',
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.country'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.state'),
        ),
    ]
