# Generated by Django 5.0.2 on 2024-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_duration_months_customerplan_duration_in_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='legal_name',
            field=models.CharField(max_length=55, verbose_name='negal Name'),
        ),
    ]
