# Generated by Django 5.0.3 on 2024-04-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='legal_name',
            field=models.CharField(max_length=255, verbose_name='Legal Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prospect',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_prospect', to='prospect.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_name',
            field=models.CharField(max_length=30, verbose_name='Short Name or Abbreviation'),
        ),
    ]
