# Generated by Django 5.0.3 on 2024-04-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_profile_display_name_alter_profile_legal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
