# Generated by Django 4.1 on 2024-03-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerplan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='customer.customerinfo'),
        ),
    ]
