# Generated by Django 5.0.2 on 2024-03-16 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_subscribedplan_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedplan',
            options={'ordering': ('customer__legal_name',)},
        ),
        migrations.AlterField(
            model_name='subscribedplan',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_plan', to='customer.profile'),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('invoice_no', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='customer.profile')),
            ],
        ),
    ]
