# Generated by Django 5.0.2 on 2024-03-17 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_subscribedplan_options_and_more'),
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prospect',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospect.profile'),
        ),
    ]
