# Generated by Django 5.0.2 on 2024-03-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customerinfo_legal_name'),
        ('customer', '0004_alter_customerplan_customer'),
    ]

    operations = [
    ]
