# Generated by Django 5.0.3 on 2024-05-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_paymenthistory_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='receipt_no',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='invoice_no',
            field=models.CharField(max_length=25),
        ),
    ]
