# Generated by Django 5.0.2 on 2024-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_profile_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
