# Generated by Django 5.0.3 on 2024-05-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_paymenthistory_receipt_no_paymenthistory_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='invoice_no',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='receipt_no',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
