# Generated by Django 5.0.3 on 2024-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_paymenthistory_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
