# Generated by Django 5.0.3 on 2024-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_userapppermissions_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedplan',
            options={'ordering': ('customer__official_name',)},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='short_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='official_name',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_name',
            field=models.CharField(default='2', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
    ]
