# Generated by Django 5.0.2 on 2024-03-17 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_paymenthistory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='1', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
    ]
