# Generated by Django 5.0.3 on 2024-05-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_paymenthistory_due_date_and_more'),
        ('customer', '0007_alter_subscribedplan_options_and_more'),
    ]

    operations = [
    ]
