# Generated by Django 5.0.2 on 2024-03-16 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customeruser_userapppermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerplan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_plans', to='customer.customerinfo'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to='customer.customerinfo'),
        ),
    ]
