# Generated by Django 5.0.3 on 2024-05-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_merge_20240525_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
