# Generated by Django 4.1 on 2024-02-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('profile_picture', models.ImageField(upload_to='contact/profile_pictures')),
                ('designation', models.CharField(max_length=55)),
                ('organization', models.CharField(max_length=55)),
                ('mobile_number', models.BigIntegerField()),
                ('alt_number', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
