# Generated by Django 4.1 on 2024-02-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='contact/profile_pictures'),
        ),
    ]
