# Generated by Django 4.1 on 2024-02-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(upload_to='contact/profile_pictures'),
        ),
    ]
