# Generated by Django 5.0.2 on 2024-03-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_contact_created_at_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
    ]
