# Generated by Django 5.0.3 on 2024-04-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',), 'verbose_name': 'state', 'verbose_name_plural': 'states'},
        ),
    ]
