# Generated by Django 5.0.2 on 2024-02-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plan_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=55, verbose_name='Plan Type')),
                ('no_of_members', models.CharField(max_length=55, verbose_name='Number of Members')),
                ('duration', models.CharField(max_length=50, verbose_name='Subscription Duration')),
                ('amount', models.CharField(max_length=255, verbose_name='Amount to be Payed')),
            ],
        ),
    ]
