# Generated by Django 4.1 on 2024-02-24 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.planname')),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.CharField(max_length=255)),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.number')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.planname')),
            ],
        ),
        migrations.AlterField(
            model_name='plan_info',
            name='amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.amount', verbose_name='Amount to be  Payed'),
        ),
        migrations.AlterField(
            model_name='plan_info',
            name='no_of_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.number', verbose_name='Number of Members'),
        ),
        migrations.AlterField(
            model_name='plan_info',
            name='plan_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.planname', verbose_name='Plan Type'),
        ),
    ]
