# Generated by Django 4.1 on 2024-02-24 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_planname_number_amount_alter_plan_info_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dur', models.CharField(choices=[('6 Months', '6'), ('1 Year', '12')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='amount',
            name='dur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.duration'),
        ),
        migrations.AlterField(
            model_name='plan_info',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.duration', verbose_name='Duration'),
        ),
    ]
