# Generated by Django 4.1 on 2024-02-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_plan_info_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_info',
            name='duration',
            field=models.CharField(choices=[('6 Months', '6'), ('1 Year', '12')], max_length=10),
        ),
    ]
