# Generated by Django 4.1 on 2024-02-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_alter_plan_info_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='num',
            field=models.CharField(max_length=30),
        ),
    ]
