# Generated by Django 4.1 on 2024-02-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_alter_number_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_info',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plan_info',
            name='duration',
            field=models.CharField(choices=[(6, '6 Months'), (12, '1 Year')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
