# Generated by Django 4.1 on 2024-02-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_alter_plan_info_amount_alter_plan_info_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_info',
            name='duration',
        ),
    ]
