# Generated by Django 5.0.2 on 2024-03-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=55, verbose_name='Full Name')),
                ('designation', models.CharField(max_length=55, verbose_name='Designation')),
                ('dailing_code', models.CharField(choices=[('India', '+91'), ('USA', '+1'), ('UK', '+44')], max_length=10)),
                ('mobile_no', models.CharField(max_length=50, verbose_name='Mobile Number')),
            ],
        ),
    ]
