# Generated by Django 5.0.3 on 2024-03-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
